### ISSUE TITLE
 getActualWorkLabor() and  getBudgetWorkLabor() in .NET

### ISSUE THREAD

**Issue by iMohannad** [joniles/MPXJ.Net#13]
Hi, 

I do not see a variable in Task.cs that matches javaapi docs of getActualWorkLabor() and geteBudgetWorkLabor().

How can I get these values from a Task object in MPXJ.Net?

Thank you

**Comment by joniles** [comment]
Ah! I've not being doing a good enough job of keeping the MPXJ.Net interface in sync with MPXJ (note to self: must invest some time into tooling to automate/check this!)

Anyhow, I will put together a new release with the missing properties.

You can work around this with something like:

```c#
var value = task.JavaObject.get(net.sf.mpxj.TaskField.ACTUAL_WORK_LABOR)
```

but you'll be getting back a Java type rather than a c# type.

**Comment by joniles** [comment]
Hi, I've merged the changes to add the missing attributes, these will be available in the next MPXJ release.
